stages:
    - build
    - test
    - deploy
      
image: docker:stable

services:
    - docker:18.09-dind

before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_KEY
    - apk add python python-dev py-pip libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose


build:
    stage: build
    script:
        - docker-compose build
        - docker-compose up -d
