stages:
    - build
    - test
    - deploy

image: docker:stable

services:
    - docker:dind

before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_KEY"
    - docker info

build:
    stage: build
    image: docker/compose:latest
    script:
        - docker-compose build
        - docker-compose up -d
