stages:
    - build
    - test
    - deploy

image: docker:stable

services:
    - docker:dind

before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_KEY
    - apk add python python-dev py-pip build-base
    - pip install docker-compose


build:
    stage: build
    script:
        - 
        - docker-compose build
        - docker-compose up -d
