stages:
    - build
    - test
    - deploy

image: docker:latest

services:
    - docker:latest-dind

before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_KEY
    - docker info

build:
    stage: build
    script:
        - docker-compose build
        - docker-compose up -d
    
