stages:
    - build
    - test
    - deploy
      
image: docker:19.03.8

variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"


services:
    - docker:19.03.8-dind

before_script:
    - docker info
    - docker login -u $DOCKER_USER -p $DOCKER_KEY
    - apk add python python-dev py-pip libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose


build:
    stage: build
    script:
        - docker-compose build
        - docker-compose up -d
