stages:
    - build
    - test
    - deploy

image: docker/compose:latest

services:
    - docker:dind

before_script:
    - docker info

build:
    stage: build
    script:
        - docker-compose build
        - docker-compose up -d
