stages:
    - build
    - test
    - deploy
      
image: docker:stable


services:
    - docker:dind


build:
    stage: build
    script:
        - docker login -u $DOCKER_USER -p $DOCKER_KEY
        - docker build -t client ./client
        - docker-compose build
        - docker-compose up -d
