stages:
    - build
    - test
    - deploy

variables:
    DOCKER_HOST: tcp://localhost:2375

image: docker:stable

services:
    - docker:dind

before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_KEY
    - docker info

build:
    stage: build
    script:
        - docker-compose build
        - docker-compose up -d
