version: '3.8' 

services:
    angular-client:
        build: ./client
        ports:
            - "4200:4200"
        volumes:
            - ./client/src:/usr/src/app/src
 
    express-server:
        build: ./server
        ports:
            - "8080:8080" 
        environment:
            - MONGO_URL=mongodb://database/anotherplanningtool
        links:
            - mongo-database
        depends_on:
            - mongo-database
 
    mongo-database:
        image: mongo
        volumes:
            - "/data/db:/data/db"
        ports:
            - "27017:27017"