version: '3.8' 
 
services:
    angular-client:
        build: ./client
        ports:
            - "80:4200"
 
    express-server:
        build: ./server
        ports:
            - "8080:8080" 
        environment:
            - MONGO_URL=mongodb://database/anotherplanningtool
        links:
            - mongo-database
        depends_on:
            - mongo-database
 
    mongo-database:
        image: mongo
        volumes:
            - "/data/db:/data/db"
        ports:
            - "27017:27017"